baseURL = 'https://erbaafidotama-blog.netlify.app/id'
languageCode = 'id-ID'
title = 'Erba Afidotama Personal Website'
theme = 'anatole'

[params]
title = "I'm Erba Afidotama"
description = """
I'm Web Developer
Full Stack
"""
profilePicture = "/poo.png"
copyright = "2020-{{ YEAR }} | Theme by Anatole"
readMore = true

[taxonomies]
  category = 'categories'
  tag = 'tags'

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/erba-afidotama-b5641b87"
[[params.socialIcons]]
icon = "fab fa-github"
title = "Linkedin"
url = "https://github.com/erbaafidotama"
[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Linkedin"
url = "https://twitter.com/erbaa_e"
[[params.socialIcons]]
icon = "fab fa-telegram-plane"
title = "Linkedin"
url = "https://t.me/erbaafidotama"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Blog"
  weight = 200
  identifier = "blog"
  url = "/blog/"

  [[menu.main]]
  name = "Project"
  weight = 300
  identifier = "project"
  url = "/projects/"
